# Generated by Django 4.1 on 2023-12-19 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gps", "0002_tracker_vehicle_tracker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="tracker",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="gps.tracker"
            ),
        ),
    ]
